[package]
name = "bft_interp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bft_types = { version = "0.1.0", path = "../bft_types" }