name: Rust checks
on: push
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo check
        run: cd bft && cargo check --all
  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cd bft && cargo fmt --all --check
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cd bft && cargo test --all
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cd bft && cargo clippy --all-targets --all-features
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docs
        run: cd bft && cargo doc --all
      - uses: actions/upload-artifact@v3
        with:
          name: rustdoc
          path: bft/target/doc
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: bft/target/doc
      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v1
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run Tarpaulin
        run: cd bft && cargo tarpaulin --all
