name: Docs
on:
  push:
    branches:
      - main
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Build Docs
        run: cd bft && cargo doc --all
      - name: Make index.html a link to help.html
        run: cd bft/target/doc && ln -s help.html index.html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: bft/target/doc
      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v1
